version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#  flyway:
#    image: boxfuse/flyway:5-alpine
#    command: -url=jdbc:postgresql://postgres_database:5432/ -connectRetries=1 migrate -X
#    volumes:
#      - ./migration:/resource/db/migration
#    depends_on:
#      - db

#  api:
#    build: .\
#    ports:
#      - "8191:8191"
#    environment:
#      NODE_ENV: production
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: postgres_database
#    links:
#      - db
#    volumes:
#      - './:/src'
volumes:
  db:
    driver: local


